### ISSUE TITLE
Kill SPARCS SSO v1

### ISSUE THREAD

**Issue by a1sams1a** [sparcs-kaist/sparcssso#106]
SPARCS SSO v1을 지원 중단시킨다.
지원 중지 시기는 대략 8월 말 정도가 될 것

**Comment by leeopop** [comment]
8월 말 지남

**Comment by a1sams1a** [comment]
@leeopop 현재 otlplus가 아직도 v1을 사용하고 있어서 지원 중단할 수 없습니다. @ashe님 및 @kangwon님이 v2로 업그레이드 중입니다.

**Comment by ashe-sparcs** [comment]
죄송합니다 오늘내로 업그레이드하겠습니다
