### ISSUE TITLE
upgrade to python3

### ISSUE THREAD

**Issue by a1sams1a** [sparcs-kaist/sparcssso#110]
대략 다음 순서로 진행할 예정
- pycon 가서 python 2.7을 쓴다고 말하기
- 어그로 끌려 뺨 맞고 python 3 설교받기
- 맥주 마시며 울면서 코딩하기

**Comment by leeopop** [comment]
파이콘 오는사람들 대부분 2.7쓰지않을까 현실적으로

**Comment by a1sams1a** [comment]
다음과 같은 문제가 있어 python3으로의 migration을 취소합니다.
1. 베타 서버를 위해 mod_wsgi python3 버전을 사용해보았으나 기존 실서버와 충돌하였음
2. 기본적으로 설치되는 mod_wsgi python3을 사용하였을 때 3.2 기준으로 설치되며 3.5를 위해서는 build해야 함
3. mod_uwsgi 또는 mod_wsgi를 pip를 통해 설치하고 apache2의 backend로 사용하는 방법으로 버전 문제를 피할 수 있음
4. 그러나 3을 수행하기 위해서는 서비스 중단 및 시간이 필요하지만 방학이 끝나감
5. 따라서 python3으로의 migration을 중단하고 commit;4808a2bd6df0e6ff7ef33f7aac4b7bee4da38faf 을 롤백할 예정임
