### ISSUE TITLE
increase timeout of api v2 

### ISSUE THREAD

**Issue by a1sams1a** [sparcs-kaist/sparcssso#135]
hmac timestamp diff: 3 sec -> 5 sec
login token expire: 5 sec -> 10 sec
point modify limit rate: 1 req / 5 sec -> 1 req / 10 sec

**Comment by leeopop** [comment]
포인트 증가가 10초에 1번이면 되나?

**Comment by a1sams1a** [comment]
@leeopop replay attack을 피하기 위해 10초 안에 포인트 증가 요청을 2번 보낼 수 없도록 제한합니다. OTL+와 ARA+(서비스될지 모르겠지만) 등등의 포인트 기준이 다를 수 있어 처음부터 환전하는 개념으로 만들었습니다...

**Comment by leeopop** [comment]
만약에 댓글 1개당 포인트 1 이런식이면 좀 힘들 수 있을 것 같은데 
DoS 공격이 아니면 timeout 이 없다고 replay attack 이 가능한가?
SSL 단에서 알아서 차단될 것 같은데..

**Comment by leeopop** [comment]
만약에 한다면 1분내에 20개 식으로 burst 를 좀 더 허용하는게 나아 보이는데

**Comment by a1sams1a** [comment]
/api/ 부분에서는 ECDHE를 사용하면 안전할 거 같네요. http://security.stackexchange.com/questions/20105/are-ssl-encrypted-requests-vulnerable-to-replay-attacks

**Comment by a1sams1a** [comment]
https://httpd.apache.org/docs/2.4/ssl/ssl_howto.html#strongurl 를 설정해서 /api/ 부분에서만 ECDHE 사용을 강제할 수 있을 거 같습니다. 다시 확인 후 timeout 삭제하겠습니다.

**Comment by a1sams1a** [comment]
point modify limit rate: 1 req / 5 sec -> X (refer #137)
