### ISSUE TITLE
Unified rate limit module

### ISSUE THREAD

**Issue by leeopop** [sparcs-kaist/sparcssso#139]
시간날때 한번 만들어보는건?
https://django-ratelimit.readthedocs.io/en/latest/
이거 참고해서 해도 좋은데 얼핏 보니까 저기 per-user limit 가 되는지 모르겠네

**Comment by leeopop** [comment]
이미 요청이 있긴 했었네
https://github.com/jsocol/django-ratelimit/issues/52

여기 기여해보고 반영되면 써보는걸로?

**Comment by a1sams1a** [comment]
오 좋은 패키지네요 근데 rate limit을 어디다가 써야 하나요...?

**Comment by leeopop** [comment]
그냥 모든 api에 적용시켜놓고 나중에 돈내면 풀어주는.... 아 별론가 ㅋㅋ

**Comment by a1sams1a** [comment]
네....? SSO API는 SPARCS 서비스들 서버가 사용하는거라서요....

**Comment by leeopop** [comment]
http://django-ratelimit.readthedocs.io/en/latest/rates.html#callables

이미 구현되어있네

**Comment by a1sams1a** [comment]
근데 이거 진짜 필요한가요...? @leeopop
