### ISSUE TITLE
릴리즈를 위해 Facebook, Twitter 연동 작업 마무리

### ISSUE THREAD

**Issue by ghghgh777** [sparcs-kaist/sparcssso#15]
필요한 과정 : 
1. Facebook, Twitter에 SPARCS 계정 만들기
2. 해당 계정을 통해 App ID 발급 받기
3. 코드 내의 App ID(현재는 테스트용 App ID 사용중)를 수정

**Comment by a1sams1a** [comment]
Facebook, Twitter App ID 발급 및 적용 완료
