### ISSUE TITLE
SPARCS SSO 도메인 발급받기

### ISSUE THREAD

**Issue by ghghgh777** [sparcs-kaist/sparcssso#16]
현재 SPARCS SSO는 bit 서버에서 테스트가 이루어지고 있습니다. ARA+ 역시 마찬가지입니다. 그런데 django에서 세션을 저장해놓는 쿠키가 도메인 주소만 구별하고 포트는 구별하지 않기 때문에, 원래는

ARA+ 로그인 요청 -> SPARCS SSO에서 로그인 -> ARA+에서 로그인

의 과정을 거친 뒤 SPARCS SSO에 재접속했을 때 로그인이 된 상태여야 함에도 불구하고 ARA+의 로그인 정보를 저장하는 탓에 SPARCS SSO의 로그인 정보가 유실되는 문제가 발생하고 있습니다. 이에 따라 SPARCS SSO를 실제 서버 또는 bit를 제외한 테스트 서버에서 돌려보아야 할 필요가 있습니다.

이 경우 수정할 부분은 다음과 같습니다. 이메일 인증, 비밀번호 재설정 시에 발송되는 이메일의 내용 역시 같이 수정해야 합니다. (현재는 bit.sparcs.org:port 식으로 발송하고 있습니다.)

단, ARA+와 도메인을 분리하기만 하면 정상 작동할 것으로 보여 시급한 문제는 아닌 듯합니다.

**Comment by a1sams1a** [comment]
http://sso.sparcs.org/
