### ISSUE TITLE
OAuth 권한 수정

### ISSUE THREAD

**Issue by StoryKim** [sparcs-kaist/sparcssso#17]
페이스북은 에러때문에 확인을 못해봤는데,
트위터의 경우 필요도 없는 권한을 요구하고 있음
( 타임라인의 트윗보기, 누구를 팔로우하는지 보기 )

**Comment by a1sams1a** [comment]
해당 권한은 twitter api의 최소 권한으로, 더 이상 권한 축소가 불가능함
