### ISSUE TITLE
Code of Conduct

### ISSUE THREAD

**Issue by samjo-nyang** [sparcs-kaist/sparcssso#190]
다음 Code of Conduct를 SPARCS SSO에 적용시키려고 합니다.
- https://github.com/twitter/code-of-conduct/blob/master/code-of-conduct.md

적용 범위는 다음과 같습니다.
- SPARCS SSO Code Contribution
- SPARCS SSO SYSOP Activities

의견 있으시면 이 issue에 댓글로 남겨주시기 바랍니다.
- 찬성 의견일 경우에도 댓글 남겨주세요.

@samjo-nyang, @ghghgh777, @quark325, @Shavakan, @pipoket, @ashe-sparcs, @todoaskit

**Comment by todoaskit** [comment]
저는 좋다고 생각합니다.

**Comment by samjo-nyang** [comment]
변경되었습니다. Twitter의 Code of Conduct 대신 http://contributor-covenant.org/version/1/4/을 적용하고자 합니다. 의견주세요. @samjo-nyang, @ghghgh777, @quark325, @Shavakan, @pipoket, @ashe-sparcs, @todoaskit

**Comment by YujinGaya** [comment]
좋습니다

**Comment by samjo-nyang** [comment]
적용되었습니다.
