### ISSUE TITLE
카이스트 포탈 사이트로 접속할 필요 없이 바로 포탈 sso 인증

### ISSUE THREAD

**Issue by steinkim** [sparcs-kaist/sparcssso#204]
1. https://univote.co.kr/ 같은 곳을 보면 포탈 사이트로 이동할 필요없이 바로 자체 입력 폼에서 포탈 인증이 가능한데 SPARCS SSO의 경우도 이렇게 바꾸면 어떨까합니다.

2. 이건 제 추측이지만 다수의 학생들이 portal 인증을 통해 sparcssso로 로그인을 할 것이므로, 현재의 이메일로 로그인하는 폼과 포탈인증의 자리를 바꾸어

포탈 ID: ----------------
포탈 비밀번호: --------
이메일로 로그인
페이스북 로그인
트위터로 로그인

과 같은 형태로 바꾸면 어떨까 싶습니다. 이건 UI 상의 혼동을 초래할 수도 있으니, 포탈 로그인하는 depth를 줄일 수 있는 다른 방법이 있으면 그걸 사용해도 좋을 듯 싶습니다(현재보다 1 적게).

**Comment by talkwithraon** [comment]
https://univote.co.kr 개발자입니다. 현재 sparcssso는 ksso v3를 쓰고 있고, univote는 ksso v2를 쓰고 있습니다. 보안적인 면에서 ksso v3가 압도적으로 옳은 방식이므로 사용자 편의를 위해서 v2로 다운 그레이드 하는 것이 좋은 방식일 것이라 생각하지 않습니다. 게다가 v2의 경우에는 키 발급이 중단된 상태입니다. 제가 쓰고 있는 키 또한 만료 예정이라 조만간 v3로 갈아탈 예정입니다.

**Comment by steinkim** [comment]
v3의 경우는 반드시 포탈 창을 거쳐야 하나요?

**Comment by talkwithraon** [comment]
그렇습니다. 제3자 사이트에 의해 포탈 계정 인증 정보가 갈취될 수 있기 때문입니다. 실제로 vote.kaist.ac.kr이나 clubmem.kaist.ac.kr 등의 사이트 운영을 하면서 보안상 불안하다는 지적을 많이 받았습니다.

**Comment by talkwithraon** [comment]
http://ctreq.kaist.ac.kr/static/docs/guide.pdf 는 제가 5년 전에 아카이빙용으로 남겨둔 링크인데 도대체 어디서 얻으신건가요 ㄷㄷ

문서 원하시면 슬랙으로 공유드리겠습니다.

**Comment by steinkim** [comment]
넵 슬랙에 부탁드립니다. 이 이슈는 닫도록 하겠습니다.
