### ISSUE TITLE
Django 2.2

### ISSUE THREAD

**Issue by apple12347678** [sparcs-kaist/sparcssso#231]
Released in April 1st, 2019.

Some functions have changed its parameters.

**Comment by jungnoh** [comment]
안녕하세요, 올해 새로운 PM입니다. 이 이슈는 제가 가져가겠습니다.

**Comment by apple12347678** [comment]
@jungnoh 안녕하세요. 관련 업무로 연락이 한참 끊겼었는데 PM이 다시 생겼다니 다행입니다. 제가 담당하던 티켓들 중 불필요한 것들은 그대로 닫아도 될까요? 인수인계나 리뷰 필요하신지도 궁금합니다. (제가 리뷰할 자격이 되는지는 모르겠지만...)

**Comment by jungnoh** [comment]
티켓은 닫아주셔도 괜찮습니다.
개발이 다소 정체되어 있는 상태라 봄에 팀을 새롭게 꾸려서 개발을 이어가 보려고 하고 있습니다. 우선은 프런트엔드 리팩토링 (#230)을 생각중인데, 기존 팀원분들께서 어떤 계획이나 아이디어가 있으셨는지 궁금합니다. 저도 코드를 알아가고 있는 단계라서, 이외에도 리뷰나 피드백 주시면 많은 도움이 될 것 같습니다ㅎㅎ

**Comment by apple12347678** [comment]
답변 감사합니다. 혹시 슬랙으로 대화 가능하실까요? 아니면 어떤 수단으로 연락하는 것이 편하실까요? 이슈에서 전부 말씀드리기에는 공간이 부족한 것 같네요.

**Comment by jungnoh** [comment]
슬랙 채널이나 dm으로 연락 부탁드립니다.
