### ISSUE TITLE
Point Lock

### ISSUE THREAD

**Issue by a1sams1a** [sparcs-kaist/sparcssso#26]
Point Lock을 만들어야 한다.
추후 스펙 결정

**Comment by Suckzoo** [comment]
과연 lock을 걸어야 할 정도로 request가 동시에 올 가능성이 얼마나..? 동시에 댓글 달기 버튼을 누르지 않는 한 글쎄....

**Comment by a1sams1a** [comment]
그냥 클라이언트로 일거리를 미룰가요...?

**Comment by Suckzoo** [comment]
굳이 할 이유가 있을까 싶음... 한 유저가 동시에 리퀘스트를 두 개 이상 쏠 가능성이 나는 거의 없다고 보는데 어떻게 생각하는지?

**Comment by a1sams1a** [comment]
spec:
-> 동일 API에 추가합니다.
-> add input param: lock (optional) - true or false
-> add input param: lower_bound (optional) - number
-> add output param: changed - true or false

delta가 0일 경우: 현재 포인트 가져오기, changed = false
delta가 0이 아니며 lock이 아닐 경우: 무조건 변경, changed = true
delta가 0이 아니며 lock일 경우: 현재 포인트가 lower_bound 이상일 경우만 변경, changed = true / false
