### ISSUE TITLE
pep8 맞추기

### ISSUE THREAD

**Issue by a1sams1a** [sparcs-kaist/sparcssso#34]
pep8에 맞춰야 한다.
E501 - line length 제외
E731 - def, not lambda 제외

**Comment by ktk1012** [comment]
pep8...

**Comment by a1sams1a** [comment]
oh... such... stupid... ㅁㄴㅇㄹ

**Comment by Suckzoo** [comment]
나는 빡빡이다 3창하세요.

**Comment by a1sams1a** [comment]
나는 빡빡이다 나는 빡빡이다 나는 빡빡이다
