### ISSUE TITLE
해지 거부 기능

### ISSUE THREAD

**Issue by a1sams1a** [sparcs-kaist/sparcssso#35]
SSO에서 서비스 해지를 거부할 수 있도록 해야 할까요? 의견바랍니다.

**Comment by a1sams1a** [comment]
required by project jangteo

**Comment by Suckzoo** [comment]
아까 언급했다시피 서비스별 세부 규정에 따른다는 사실만 명시하면 되지 않을까요

**Comment by a1sams1a** [comment]
넹넹
(i) 어떻게 오류 메시지를 전달할건지 포맷 결정
(ii) 오류 메시지를 띄우는 코드 작성
(iii) 약관 개정

**Comment by a1sams1a** [comment]
테스트 이후에 close 할 예정입니다.
