### ISSUE TITLE
kaist_info is not in valid json

### ISSUE THREAD

**Issue by isyangban** [sparcs-kaist/sparcssso#48]
The value of the retrieved info from /api/v1/token/info/, kaist_info is not in valid json.

e.g) Returned value example
{'ku_std_no': '2015123', 'kaist_uid': '00000000', 'ku_psft_user_status_kor': u'\uc123\ud123'}
but it should be like this
{"ku_std_no": "2015123", "kaist_uid": "00000000", "ku_psft_user_status_kor": "유니코드"}

**Comment by a1sams1a** [comment]
확인하였습니다. 곧 수정 예정입니다.
