### ISSUE TITLE
SSO v2 개발

### ISSUE THREAD

**Issue by a1sams1a** [sparcs-kaist/sparcssso#76]
다음과 같은 티켓이 있음
- APP의 종류를 3개로 구분: 일반 / 개발 / 스팍스 전용
- 사용자의 포인트를 두개로 구분: 일반 / 개발
- callback 주소로 로그인하는 것을 지원하지 않음
- sparcs 회원은 신규 테스트 앱을 생성 및 삭제하는 것이 가능
- test앱에 대해 test flag가 켜져 있는 회원은 포인트 / 로그아웃 / 해지 기능을 실험할 수 있음
- 모든 secret key의 비교를 const time에 하도록 변경

**Comment by Shavakan** [comment]
와 완전 본격적이네요

**Comment by a1sams1a** [comment]
draft 1을 slack에 업로드하였습니다. 더 이상 secret key를 서버에 보내지 않으며, 주요 request에 hmac signing을 추가하였습니다.

**Comment by a1sams1a** [comment]
minor bug fix외에 issue가 없으면 8월 6-7일 deploy 예정입니다.

**Comment by a1sams1a** [comment]
- deploy 되었습니다. API v2는 내부적으로만 테스트하였고, API v1은 잘 작동하는 것을 확인하였습니다.
- 본 issue를 닫도록 하고, 앞으로 발생하는 API v2 문제는 bug으로 처리하도록 하겠습니다.
- API v1이 삭제될 때 API v2 library 버전 정보를 업데이트할 예정입니다.
